### ISSUE TITLE
missing deps during docker build

### ISSUE THREAD

**Issue by ivveh** [esabouraud/discomblebot#1]
Couldn't build with your Dockerfile as you were calling on stuff that didn't exist in the container.
Added this to solve it:
RUN apk add --update --no-cache py-configobj libusb py-pip python-dev gcc linux-headers musl-dev

**Comment by esabouraud** [comment]
Thank you for bringing this issue to my attention. An implicit dependency has probably been removed in the base image. This is fixed in https://github.com/esabouraud/discomblebot/commit/54281c4feb9a9f5f723855eafe41f171d89cb10d.
