### ISSUE TITLE
some more details regarding configuration

### ISSUE THREAD

**Issue by ivveh** [esabouraud/discomblebot#2]
Hey, could you give some examples on the configuration and requirements (like limitations of the bot?).

[discord]
#token redacted
token=abc123
#channel redacted
channel=12345678901234567890

[mumble]
server=127.0.0.1
port=64738
channel=Root
nickname=Discomblebot
password=secret

I tried to launch with these setting (I'm assuming they are not correctly put in, would be nice to know what the software is expecting without having to browse throught the code and debug it).

Also it doesn't seem to be able to mute/deafen itself.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/discomble/discomblebot/mumbot.py", line 223, in run
    bot.start_client()
  File "/discomble/discomblebot/mumbot.py", line 36, in start_client
    self.mumble.users.myself.mute()
AttributeError: 'NoneType' object has no attribute 'mute'

Same goes on the deafen. Tried to comment it out, then it just proceeds to fail with this instead:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/discomble/discomblebot/mumbot.py", line 224, in run
    bot.loop()
  File "/discomble/discomblebot/mumbot.py", line 71, in loop
    output_channel = self.mumble.channels[self.mumble.users.myself['channel_id']]
TypeError: 'NoneType' object is not subscriptable

(tested in the root channel on mumble)

I'm using the docker container with your build and the additional RUN command that I posted a few days ago.
Thanks.

**Comment by esabouraud** [comment]
The issue is not really the mute action. It just happens to be first thing the bot does once the pymumble framework says it's ready. It basically just means the bot has failed to connect to your server. 

I can reproduce the same error by setting a bad mumble server or port.

**Comment by esabouraud** [comment]
Since you mentioned that you use the included docker container, I find it odd that you use 127.0.0.1 as a mumble server address, as it would tend to indicate that you are running the mumble server in the same container.
If you are running the mumble server on your host, then you need to set the mumble server configuration accordingly.

**Comment by ivveh** [comment]
Oh yea I just kinda redacted it. But I'll look into the connecting problem, I might have a nat/firewall problem, did test with telnet. I'm also assuming the bot won't join discord unless everything works?

**Comment by ivveh** [comment]
Ok, so it seems the problem I was having was build related. I pulled latest, rebuilt and it joined mumble no problem without any nat/firewall changes. So now on to why it doesn't join discord channel. Can it join a private channel? Or some channel restrictions?

**Comment by esabouraud** [comment]
Cool. There are no particular restrictions regarding Discord. I find the procedure to set a Discord bot up is a bit convoluted however.
I followed these steps to configure access on my Discord server : https://realpython.com/how-to-make-a-discord-bot-python/#how-to-make-a-discord-bot-in-the-developer-portal. You will be able to ensure your bot's credentials are valid by using their sample.

**Comment by ivveh** [comment]
It's not generating any errors so I'm guessing it has to do with permissions from discord/discordbot. I don't own the channel so I depend on someone else helping out on that part.
